import type { Metadata } from "next";
import { Instrument_Serif, Inter } from "next/font/google";
import "@/styles/globals.scss";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin-ext"] });
const serif = Instrument_Serif({
  weight: "400",
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("bg-50 flex items-center justify-center",inter.className,serif.className)}>{children}</body>
    </html>
  );
}
